export const OBTENER_CHARACTERS_EXITO = "OBTENER_CHARACTERS_EXITO";
export const SIGUIENTE_CHARACTERS_EXITO = "SIGUIENTE_CHARACTERS_EXITO";
export const OBTENER_CHARACTER_POR_NOMBRE_EXITO = "OBTENER_CHARACTER_POR_NOMBRE_EXITO";
export const ANTERIOR_CHARACTER_EXITO = "ANTERIOR_CHARACTER_EXITO";
export const SET_WAIT = "SET_WAIT";
export const SHOW_BUTTONS = "SHOW_BUTTONS";



//import {OBTENER_CHARACTERS_EXITO} from "./../utils/constants"